// Programs (generated by shadergen) and materials: three.js-style uniforms set by name.
//
// As in three, one material can be drawn with several programs: the object decides
// (plain / InstancedMesh / SkinnedMesh), and a transparent DoubleSide material is drawn as a
// BackSide then a FrontSide pass, each its own program. So a material stores its uniform
// values and textures by name, lists the program for each variant it is used with, and keeps
// a std140 block per (variant, stage) that is rebuilt when a value changes.
//
// Block 0 of each stage holds frame values (camera, fog, sun, shadow) and material values;
// block 1 holds per-object values. Frame values and global textures (environment, shadow
// map, DFG table) are registered once and copied in when a material is bound.
#pragma once

#include "core/vec.h"
#include "gfx/gpu.h"
#include "gfx/texture.h"
#include "math/vmath.h"
#include "programs.h"

// Quality tier index into ProgramInfo.tier_variant: 0 high, 1 medium, 2 low, 3 ultra
extern int g_program_tier;

typedef struct FrameSlot { uint8_t stage; uint16_t offset; uint8_t type; uint16_t global; } FrameSlot;
typedef struct ObjSlots { int model, model_view, normal, receive_shadow; } ObjSlots;   // -1 = absent

typedef struct Program {
  ProgramId id;
  const ProgramInfo *info;
  const ProgramVariant *pv;
  SDL_GPUShader *vs, *fs;
  FrameSlot *frame_slots;
  int nframe_slots;
  ObjSlots obj[2];
} Program;

Program *program_get(ProgramId id);   // the current tier's variant; shaders created on first use
void programs_shutdown(void);

typedef enum Side { SIDE_FRONT, SIDE_BACK, SIDE_DOUBLE } Side;
typedef enum BlendMode { BLEND_NORMAL, BLEND_ADDITIVE, BLEND_CUSTOM, BLEND_NONE } BlendMode;

// program variants a material may be drawn with
typedef enum MatVariant {
  MV_PLAIN, MV_INSTANCED, MV_SKINNED,
  MV_PLAIN_BACK, MV_PLAIN_FRONT,            // transparent DoubleSide: BackSide pass, FrontSide pass
  MV_INSTANCED_BACK, MV_INSTANCED_FRONT,
  MV_BATCHED,                               // BatchedMesh
  MV_COUNT
} MatVariant;

typedef struct MatValue { char name[64]; double v[16]; UniformType type; } MatValue;
typedef struct MatTex { char name[48]; Texture *t; } MatTex;

typedef struct MatBinding {
  Program *prog;
  uint8_t *ub[2];                   // block 0 bytes, [0] vertex, [1] fragment
  int *leaf_value[2];               // per leaf: index into Material.values, -1 none
  int nleaves[2];
  int mapped_values;                // values.len when leaf_value was computed
  uint32_t version;                 // Material.version the bytes reflect
  Texture *tex[2][16];
  uint32_t tex_version;
} MatBinding;

typedef struct Material {
  const char *name;
  int id;
  ProgramId prog[MV_COUNT];         // PROG_COUNT = not available
  MatBinding bind[MV_COUNT];
  Vec(MatValue) values;
  Vec(MatTex) textures;
  uint32_t version, tex_version;

  Side side;
  bool transparent;
  BlendMode blending;
  SDL_GPUBlendFactor blend_src, blend_dst;
  SDL_GPUBlendOp blend_op;
  // custom blending alpha factors / equation (INVALID = same as colour, like three's null)
  SDL_GPUBlendFactor blend_src_alpha, blend_dst_alpha;
  SDL_GPUBlendOp blend_op_alpha;
  bool premultiplied_alpha;
  bool depth_test, depth_write, color_write;
  SDL_GPUCompareOp depth_func;     // three depthFunc (LessEqualDepth by default)
  bool polygon_offset;
  float po_factor, po_units;
  bool alpha_to_coverage;
  bool force_single_pass;
  bool visible;
  bool has_shadow_side;
  Side shadow_side;
  double alpha_test;                // > 0: this material's shadow caster needs its alpha
  Texture *shadow_alpha_map;        // (the map the depth material alpha-tests)
} Material;

// three's defaults (FrontSide, opaque, NormalBlending, depth test/write on); `plain` is the
// program for ordinary meshes (PROG_COUNT if the material is only used on other variants).
Material *mat_new(ProgramId plain, const char *name);
Material *mat_clone(const Material *m);
void mat_add_variant(Material *m, MatVariant v, ProgramId p);
// the variant for an object kind and pass (FATAL if the material lacks the program)
Program *mat_program(Material *m, MatVariant v);

void mat_set_float(Material *m, const char *name, double v);
void mat_set_int(Material *m, const char *name, int v);
void mat_set_bool(Material *m, const char *name, bool v);
void mat_set_vec2(Material *m, const char *name, V2 v);
void mat_set_vec3(Material *m, const char *name, V3 v);
void mat_set_vec4(Material *m, const char *name, V4 v);
void mat_set_color(Material *m, const char *name, Color c);
void mat_set_mat3(Material *m, const char *name, M3 v);
void mat_set_mat4(Material *m, const char *name, M4 v);
void mat_set_floats(Material *m, const char *name, const double *v, int n);   // float name[n]
void mat_set_texture(Material *m, const char *name, Texture *t);
Texture *mat_get_texture(const Material *m, const char *name);

// ---- frame globals ----
typedef enum FrameGlobal {
  G_VIEW_MATRIX, G_PROJECTION_MATRIX, G_CAMERA_POSITION, G_IS_ORTHOGRAPHIC,
  G_FOG_COLOR, G_FOG_DENSITY, G_AMBIENT_LIGHT_COLOR,
  G_DIR_LIGHT_DIRECTION, G_DIR_LIGHT_COLOR,
  G_DIR_SHADOW_INTENSITY, G_DIR_SHADOW_BIAS, G_DIR_SHADOW_NORMAL_BIAS, G_DIR_SHADOW_RADIUS, G_DIR_SHADOW_MAP_SIZE,
  G_DIR_SHADOW_MATRIX,
  G_COUNT
} FrameGlobal;
void frame_set_m4(FrameGlobal g, M4 m);
void frame_set_v3(FrameGlobal g, V3 v);
void frame_set_v2(FrameGlobal g, V2 v);
void frame_set_float(FrameGlobal g, double v);
void frame_set_bool(FrameGlobal g, bool v);

typedef enum GlobalTexture { GT_ENV_MAP, GT_SHADOW_MAP, GT_DFG_LUT, GT_COUNT } GlobalTexture;
void frame_set_texture(GlobalTexture g, Texture *t);

// Brings the binding up to date (material values, then frame values) and pushes block 0 of
// both stages and binds the samplers.
void mat_bind(Material *m, MatVariant v, SDL_GPUCommandBuffer *cb, SDL_GPURenderPass *rp);

// per-object block 1
typedef struct ObjectUniforms { M4 model, model_view; M3 normal; bool receive_shadow; } ObjectUniforms;
void program_push_object(Program *p, SDL_GPUCommandBuffer *cb, const ObjectUniforms *o);

// std140 writer (shared with fixed-function passes)
void write_leaf(uint8_t *dst, UniformType t, const double *v);
int uniform_leaf_offset(const UniformLeaf *leaves, const char *name, UniformType *type);
