// Types of the program reflection tables generated by tools/shadergen.c (gen/programs.c).
#pragma once

#include <stdint.h>

#include "shaders.h"

typedef enum UniformType {
  U_FLOAT, U_VEC2, U_VEC3, U_VEC4, U_INT, U_IVEC2, U_IVEC3, U_IVEC4, U_UINT, U_BOOL, U_MAT2, U_MAT3, U_MAT4,
} UniformType;

typedef enum SamplerType { S_2D, S_CUBE, S_3D, S_2D_SHADOW, S_2D_ARRAY, S_2D_INT, S_2D_UINT } SamplerType;

// one scalar/vector/matrix member of a std140 block, flattened ("directionalLights[0].color")
typedef struct UniformLeaf { const char *name; int offset; UniformType type; } UniformLeaf;
typedef struct SamplerSlot { const char *name; int binding; SamplerType type; } SamplerSlot;
typedef struct AttribSlot { const char *name; int location, nloc; UniformType type; } AttribSlot;

// block 0: frame + material uniforms (slot 0); block 1: per-object matrices (slot 1)
typedef struct BlockInfo { int size; const UniformLeaf *leaves; } BlockInfo;

typedef struct ProgramVariant {
  ShaderId vs, fs;
  const AttribSlot *attribs;
  BlockInfo vblock[2];
  const SamplerSlot *vsamplers;
  BlockInfo fblock[2];
  const SamplerSlot *fsamplers;
} ProgramVariant;

enum { PROGRAM_MAX_VARIANTS = 4 };
typedef struct ProgramInfo {
  const char *name;
  const char *params;      // ";map;vertexNormals;...;" material parameters the program was built with
  int nvariants;
  int tier_variant[4];   // high, medium, low, ultra -> variant index
  ProgramVariant variants[PROGRAM_MAX_VARIANTS];
} ProgramInfo;
